# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Sword4.xdc

# IP: ip/Ram2k2p/Ram2k2p.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ram2k2p || ORIG_REF_NAME==Ram2k2p} -quiet] -quiet
