# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7k325tffg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.cache/wt [current_project]
set_property parent.project_path /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/sol/ZJU/HustPC/HustPC3.3/QQ.coe
add_files /home/sol/ZJU/HustPC/HustPC3.3/keycode.coe
add_files /home/sol/ZJU/HustPC/HustPC3.3/hzkX.coe
add_files /home/sol/ZJU/HustPC/ASM/0123.coe
add_files /home/sol/ZJU/HustPC/ASM/lab2_lab3_181105_data.coe
add_files /home/sol/ZJU/HustPC/ASM/lab2_lab3_181105_inst_x.coe
read_verilog -library xil_defaultlib {
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/ALU/ALUSimplified.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/ALU/Add.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/CPUPipeline.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/ClkDiv.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/ControllerPipeline.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Utility/Debounce.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/newDisplay/Display_IO.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/IO.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Utility/MUX.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/PipeModules.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/PipeRegs.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Utility/QuWei2Addr.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/RegFile.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Core/ALU/Shift.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Output/VGAManager.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Input/ps2_keyboard.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/MotherBoard.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/ShfitReg8b.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Utility/RSTrigger.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/s_port_t.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/tx_control_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/rx_bps_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/rx_detect_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/rx_control_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/s_port_r.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/tx_bps_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/rx_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/SerialPort/tx_module.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/CP/Matrix4x4.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/Hex2Seg.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Output/GPU0.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/HexTo8SEG.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/ShfitReg65b.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/SegMap.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/Display.v
  /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/Display/SR_latch.v
}
read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/Ram2k2p/Ram2k2p.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/Ram2k2p/Ram2k2p_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/Ram1m2p/Ram1m2p.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/Ram1m2p/Ram1m2p_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ClkGen/ClkGen.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc]
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ClkGen/ClkGen.xdc]
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ZBMem/ZBMem.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ZBMem/ZBMem_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM_ooc.xdc]

read_ip -quiet /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k.xci
set_property used_in_implementation false [get_files -all /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k_ooc.xdc]

read_edif /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/src/newDisplay/Display.ngc
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/constrs_1/Sword4.xdc
set_property used_in_implementation false [get_files /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/constrs_1/Sword4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MotherBoard -part xc7k325tffg676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MotherBoard.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MotherBoard_utilization_synth.rpt -pb MotherBoard_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
