# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/works/AsmandInterface/HustPC3.2/HustPC3.2/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM.xci
# IP: The module: 'InterruptManageROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/works/AsmandInterface/HustPC3.2/HustPC3.2/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InterruptManageROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/works/AsmandInterface/HustPC3.2/HustPC3.2/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM.xci
# IP: The module: 'InterruptManageROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/works/AsmandInterface/HustPC3.2/HustPC3.2/HustPC3.0.srcs/sources_1/ip/InterruptManageROM/InterruptManageROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InterruptManageROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
