# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p.xci
# IP: The module: 'RAM16k2p' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM16k2p'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p.xci
# IP: The module: 'RAM16k2p' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/RAM16k2p/RAM16k2p_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM16k2p'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
