# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k.xci
# IP: The module: 'ROM8k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM8k'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k.xci
# IP: The module: 'ROM8k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sol/ZJU/HustPC/HustPC3.3/HustPC3.3/HustPC3.0.srcs/sources_1/ip/ROM8k/ROM8k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM8k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
